language: csharp
mono:
- latest
install:
- nuget restore
script:
- ./.ci.sh
env:
  secure: lpplGvsy44QvxU+yhgdakdFx8tQoyhH0Oysu9YCbn7YGuWr+CDhjuILxjVJOZoccFXyjGvDFgH9S/mZbCKX+xaKe0D6oPxrTGVkCHAZMCzwOuo+qxRxtyIjjlSxhwZDLwfv4nHROtbmJvTRQz5bg06x+mcYZ/HDjkrSKb4vOM+m3At05xprnfLjbEgnWHFJycqvtmcj6O8XrWRpt84dlpGFRLPyfun574gFYa6Ht3CWrdQPaSmU1TVpurKHJyHrDUGxmagA+4M1JeKFVLKWjGu6SIOfYLc9C0rmxxoSdkqoyIXYmA1tkvIzczdELOoDMosMJG6wIjaGxep2Kj19WB5FPTAXFblf5mwRZr/OC7O7TxhhpHpLxOdFiWEKsSmySYy5BWgjammbW6Bz6D66bPZ+LzwkDW0j9JTMZ9zlT9rTVIqJ0YbvsMONmXj2QdWkmqdBxRPvMQRwTpYRv23Q7GdqdrAMsVukkWITxAVPeochJp980ISpQxU5Xak0ppE7vk4ech1P9uJ7AgENXdDQFRBWhsiLaIlCifuRPZmfw29KKEWVVu7d2SAmZ3eccZ/Q1HsUwlJ+ShxW7MbGhi4SK3Cf422UDtZFw88xSqQBjOLlqD8SndOSDFNj3P8W7U7pS4f+CUXYa2RH5ZYmk2yqrqBcKDYPy/y4bqAAcISvt9IE=
